mars_robot:
  name: Bit
  land_width: 5
  land_height: 5
  init_x: 0
  init_y: 0
  init_orientation: NORTH

  error:
    command_not_valid: Um dos comandos enviandos na rota não é válido.
    position_not_valid: A rota informada leva a uma posição inválida.
    unknown: Ocorreu um problema desconhecido, para mais informações entre em contato com o suporte.